### ISSUE TITLE
Add the GitHub Topic: docpad-project

### ISSUE THREAD

**Issue by balupton** [jh3y/html5-boilerplate-jade-less-livereload.docpad#1]
https://help.github.com/articles/about-topics/

**Comment by jh3y** [comment]
Done 👍

**Comment by jh3y** [comment]
I'm not `100%` sure this skeleton would still even work 😕 

I'll try and get around to giving it a spin and an update 👍 

@jh3y

**Comment by balupton** [comment]
@jh3y should still work if the dependency versions are pinned

**Comment by jh3y** [comment]
Very true! Might be nice to give it a revisit though 😄  I've opened up an issue accordingly.
